# Generated by Django 4.2.1 on 2023-05-05 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menu_alter_menuitem_options_alter_menuitem_parent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='menu',
            new_name='menu_name',
        ),
    ]
