# Generated by Django 4.2.1 on 2023-05-05 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_rename_menu_name_menuitem_menu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='menu',
            new_name='menu_name',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.menuitem', verbose_name='parent'),
        ),
    ]
