# Generated by Django 4.2.1 on 2023-05-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_rename_menu_name_menuitem_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
